/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.playwindow.proyecto_final_tallerbasesdatos.Vistas.PanelsPersona;
import com.playwindow.proyecto_final_tallerbasesdatos.Vistas.*;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;

import javax.swing.JRadioButton;

/**
 *
 * @author daniel
 */
public class PersonalEdit extends javax.swing.JPanel {

    /**
     * Creates new form PersonalEdit
     */
    public PersonalEdit() {
        initComponents();
        grupoBuscNombre.add(RBNombres);
        grupoBuscNombre.add(RBPrimerAP);
        grupoBuscNombre.add(RBSegundoAP);
        formatosTextArea.setSoloLetras(txtNombres, 70);
        formatosTextArea.setSoloLetras(txtPrimerAP, 45);
        formatosTextArea.setSoloLetras(txtSegundoAP, 45);
        formatosTextArea.setSoloLetras(txtDepartamento, 70);
        formatosTextArea.setSoloLetras(txtEspecialidad, 70);
        formatosTextArea.setSoloLetras(txtRol, 70);
        formatosTextArea.FormatoSalario(txtSalario);
        setVaciarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    public void setVaciarComponentes(){
        grupoOpcion.clearSelection();
        grupoBuscNombre.clearSelection();
        txtDepartamento.setText("");
        txtEspecialidad.setText("");
        txtID.setText("");
        txtNombres.setText("");
        txtPrimerAP.setText("");
        txtRol.setText("");
        txtSalario.setText("");
        txtSegundoAP.setText("");
        cleantxtdisable();
    }
    private void cleantxtdisable(){
        txtDepartamento.setEditable(false);
        txtEspecialidad.setEditable(false);
        txtID.setEditable(false);
        txtNombres.setEditable(false);
        txtPrimerAP.setEditable(false);
        txtRol.setEditable(false);
        txtSalario.setEditable(false);
        txtSegundoAP.setEditable(false);
    }
    
    public void setEnableRBFromGroup(ButtonGroup grupo) {                           // Metodo para abilitar/desbilitar campos de texto en base a RB dentro de un buttonGroup
    // 1. Obtener el ButtonModel seleccionado
    ButtonModel modeloSeleccionado = grupo.getSelection();

    if (modeloSeleccionado != null) {
        // 2. Iterar sobre los botones del grupo para encontrar el JRadioButton
        Enumeration<AbstractButton> botones = grupo.getElements();
        while (botones.hasMoreElements()) {
            AbstractButton boton = botones.nextElement();
            if (boton.getModel() == modeloSeleccionado) {
                // Se encontró el JRadioButton seleccionado
                if (boton instanceof JRadioButton) {
                    JRadioButton rbSeleccionado = (JRadioButton) boton;
                    
                    // Asegúrate de limpiar y deshabilitar los otros campos primero 
                    // para emular el comportamiento de un grupo de radio buttons
                    cleantxtdisable(); 
                    
                    // 3. Llamar a tu método existente
                    setEnableRB(rbSeleccionado);
                    
                    // Opcional: enfocar el campo de texto si está habilitado
                    // if (rbSeleccionado == RBNombres) txtNombres.requestFocusInWindow();
                    // ... y así sucesivamente para los demás RBs ...

                    break; // Salir del bucle una vez encontrado
                }
            }
        }
    }
}
    
    
    public void setEnableRB(JRadioButton RBOpcion){
        boolean enable = RBOpcion.isSelected();
        if (RBOpcion == (RBDepartamento)){
            txtDepartamento.setEditable(enable);
        }else if (RBOpcion == (RBEspecialidad)){
            txtEspecialidad.setEditable(enable);
        }else if (RBOpcion ==(RBID)){
            txtID.setEditable(enable);
        }else if (RBOpcion ==(RBNombres)){
            txtNombres.setEditable(enable);
        }else if (RBOpcion == (RBPrimerAP)){
            txtPrimerAP.setEditable(enable);
        }else if (RBOpcion == (RBRol)){
            txtRol.setEditable(enable);
        }else if (RBOpcion == (RBSalario)){
            txtSalario.setEditable(enable);
        }else if (RBOpcion == (RBSegundoAP)){
            txtSegundoAP.setEditable(enable);
        }
        
    }
    
    private void convertSelected(ButtonModel model){
        boolean mod = model.isSelected();
        JRadioButton rb = new JRadioButton();
        rb.setSelected(true);
        setEnableRB(rb);
    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoOpcion = new javax.swing.ButtonGroup();
        grupoBuscNombre = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtPrimerAP = new javax.swing.JTextField();
        txtSegundoAP = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        RBID = new javax.swing.JRadioButton();
        RBNombres = new javax.swing.JRadioButton();
        RBPrimerAP = new javax.swing.JRadioButton();
        RBSegundoAP = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        RBRol = new javax.swing.JRadioButton();
        txtRol = new javax.swing.JTextField();
        Bbuscar = new javax.swing.JButton();
        BCargar = new javax.swing.JButton();
        RBDepartamento = new javax.swing.JRadioButton();
        txtDepartamento = new javax.swing.JTextField();
        RBEspecialidad = new javax.swing.JRadioButton();
        txtEspecialidad = new javax.swing.JTextField();
        RBSalario = new javax.swing.JRadioButton();
        txtSalario = new javax.swing.JFormattedTextField();
        BActualizar = new javax.swing.JButton();

        jLabel1.setText("Editar personal");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel6.setText("Forma de busqueda");

        RBID.setText("ID");
        RBID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBIDActionPerformed(evt);
            }
        });

        RBNombres.setText("Nombres");
        RBNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBNombresActionPerformed(evt);
            }
        });

        RBPrimerAP.setText("Primer apellido");
        RBPrimerAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBPrimerAPActionPerformed(evt);
            }
        });

        RBSegundoAP.setText("Segundo apellido");
        RBSegundoAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBSegundoAPActionPerformed(evt);
            }
        });

        jLabel2.setText("Editar o cambiar");

        RBRol.setText("Rol");
        RBRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBRolActionPerformed(evt);
            }
        });

        Bbuscar.setText("Buscar");

        BCargar.setText("Cargar");

        RBDepartamento.setText("Departamento");
        RBDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBDepartamentoActionPerformed(evt);
            }
        });

        RBEspecialidad.setText("Especialidad");
        RBEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBEspecialidadActionPerformed(evt);
            }
        });

        RBSalario.setText("Salario");
        RBSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBSalarioActionPerformed(evt);
            }
        });

        BActualizar.setText("Actualizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(312, 312, 312)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBID)
                            .addComponent(RBNombres)
                            .addComponent(RBPrimerAP)
                            .addComponent(RBSegundoAP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtPrimerAP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtID, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSegundoAP))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BCargar)
                            .addComponent(Bbuscar))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBDepartamento)
                            .addComponent(RBEspecialidad)
                            .addComponent(RBSalario)
                            .addComponent(RBRol))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSalario, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(txtEspecialidad)
                            .addComponent(txtDepartamento)
                            .addComponent(txtRol))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(BActualizar)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBID)
                    .addComponent(RBRol)
                    .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BCargar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RBNombres)
                            .addComponent(RBDepartamento)
                            .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrimerAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RBPrimerAP)
                            .addComponent(RBEspecialidad)
                            .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bbuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BActualizar)
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSegundoAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBSegundoAP)
                    .addComponent(RBSalario)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RBIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBIDActionPerformed
        setEnableRB(RBID);
    }//GEN-LAST:event_RBIDActionPerformed

    private void RBRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBRolActionPerformed
        setEnableRB(RBRol);
    }//GEN-LAST:event_RBRolActionPerformed

    private void RBDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBDepartamentoActionPerformed
        setEnableRB(RBDepartamento);
    }//GEN-LAST:event_RBDepartamentoActionPerformed

    private void RBNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBNombresActionPerformed
        setEnableRBFromGroup(grupoBuscNombre);
    }//GEN-LAST:event_RBNombresActionPerformed

    private void RBPrimerAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBPrimerAPActionPerformed
        setEnableRBFromGroup(grupoBuscNombre);
    }//GEN-LAST:event_RBPrimerAPActionPerformed

    private void RBSegundoAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBSegundoAPActionPerformed
        setEnableRBFromGroup(grupoBuscNombre);
    }//GEN-LAST:event_RBSegundoAPActionPerformed

    private void RBEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBEspecialidadActionPerformed
        setEnableRB(RBEspecialidad);
    }//GEN-LAST:event_RBEspecialidadActionPerformed

    private void RBSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBSalarioActionPerformed
        setEnableRB(RBSalario);
    }//GEN-LAST:event_RBSalarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActualizar;
    private javax.swing.JButton BCargar;
    private javax.swing.JButton Bbuscar;
    private javax.swing.JRadioButton RBDepartamento;
    private javax.swing.JRadioButton RBEspecialidad;
    private javax.swing.JRadioButton RBID;
    private javax.swing.JRadioButton RBNombres;
    private javax.swing.JRadioButton RBPrimerAP;
    private javax.swing.JRadioButton RBRol;
    private javax.swing.JRadioButton RBSalario;
    private javax.swing.JRadioButton RBSegundoAP;
    private javax.swing.ButtonGroup grupoBuscNombre;
    private javax.swing.ButtonGroup grupoOpcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPrimerAP;
    private javax.swing.JTextField txtRol;
    private javax.swing.JFormattedTextField txtSalario;
    private javax.swing.JTextField txtSegundoAP;
    // End of variables declaration//GEN-END:variables
}
