/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.playwindow.proyecto_final_tallerbasesdatos.Vistas.PanelsPersona;

/**
 *
 * @author daniel
 */
public class PersonaEdit extends javax.swing.JPanel {

    /**
     * Creates new form PersonaEdit
     */
    public PersonaEdit() {
        initComponents();
    }
    
    public void setVaciarComponentes(){
        txtNombres.setText("");
        txtPrimerAP.setText("");
        txtSegundoAP.setText("");
        txtFechaNaci.setText("YYYY-MM-DD");
        txtTelefono.setText("00+ 000 000 0000");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtPrimerAP = new javax.swing.JTextField();
        txtSegundoAP = new javax.swing.JTextField();
        txtFechaNaci = new javax.swing.JFormattedTextField();
        txtTelefono = new javax.swing.JFormattedTextField();
        RBNombres = new javax.swing.JRadioButton();
        RBPrimerAP = new javax.swing.JRadioButton();
        RBSegundoAP = new javax.swing.JRadioButton();
        RBFechaNaci = new javax.swing.JRadioButton();
        RBTelefono = new javax.swing.JRadioButton();

        jLabel1.setText("Editar persona");

        RBNombres.setText("Nombres");

        RBPrimerAP.setText("Primer apellido");

        RBSegundoAP.setText("Segundo apellido");

        RBFechaNaci.setText("Fecha de nacimiento");

        RBTelefono.setText("Telefono de contacto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RBNombres)
                            .addComponent(RBPrimerAP)
                            .addComponent(RBSegundoAP)
                            .addComponent(RBFechaNaci)
                            .addComponent(RBTelefono))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(txtFechaNaci)
                            .addComponent(txtSegundoAP)
                            .addComponent(txtPrimerAP)
                            .addComponent(txtNombres))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtPrimerAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtSegundoAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RBNombres)
                        .addGap(11, 11, 11)
                        .addComponent(RBPrimerAP)
                        .addGap(11, 11, 11)
                        .addComponent(RBSegundoAP)
                        .addGap(11, 11, 11)
                        .addComponent(RBFechaNaci)
                        .addGap(11, 11, 11)
                        .addComponent(RBTelefono)))
                .addGap(150, 150, 150))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RBFechaNaci;
    private javax.swing.JRadioButton RBNombres;
    private javax.swing.JRadioButton RBPrimerAP;
    private javax.swing.JRadioButton RBSegundoAP;
    private javax.swing.JRadioButton RBTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JFormattedTextField txtFechaNaci;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPrimerAP;
    private javax.swing.JTextField txtSegundoAP;
    private javax.swing.JFormattedTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
