/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.playwindow.proyecto_final_tallerbasesdatos.Vistas.PanelsPersona;

import com.playwindow.proyecto_final_tallerbasesdatos.Vistas.formatosTextArea;
import javax.swing.JRadioButton;

/**
 *
 * @author daniel
 */
public class PersonaEdit extends javax.swing.JPanel {

    /**
     * Creates new form PersonaEdit
     */
    public PersonaEdit() {
        initComponents();
        formatosTextArea.setSoloLetras(txtNombres, 70);
        formatosTextArea.setSoloLetras(txtPrimerAP, 45);
        formatosTextArea.setSoloLetras(txtSegundoAP, 45);
        formatosTextArea.FormatoFecha(txtFechaNaci);
        formatosTextArea.FormatoTelefono(txtTelefono);
    }
    
    public void setVaciarComponentes(){
        txtNombres.setText("");
        txtPrimerAP.setText("");
        txtSegundoAP.setText("");
        txtFechaNaci.setText("YYYY-MM-DD");
        txtTelefono.setText("00+ 000 000 0000");
        txtDNI.setText("");
        groupBuscar.clearSelection();
        RBFechaNaci.setSelected(false);
        RBNombres.setSelected(false);
        RBPrimerAP.setSelected(false);
        RBSegundoAP.setSelected(false);
        RBTelefono.setSelected(false);
        
        setEnabletextField(RBNombres);
        setEnabletextField(RBPrimerAP);
        setEnabletextField(RBSegundoAP);
        setEnabletextField(RBFechaNaci);
        setEnabletextField(RBTelefono);
    }
    
    private void setEnabletextField(JRadioButton select){
        boolean enablede = select.isSelected();
        if (select.equals(RBFechaNaci)){
            txtFechaNaci.setEditable(enablede);
        }else if (select.equals(RBNombres)){
            txtNombres.setEditable(enablede);
        }else if (select.equals(RBPrimerAP)){
            txtPrimerAP.setEditable(enablede);
        }else if (select.equals(RBSegundoAP)){
            txtSegundoAP.setEditable(enablede);
        }else if (select.equals(RBTelefono)){
            txtTelefono.setEditable(enablede);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        groupBuscar = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtPrimerAP = new javax.swing.JTextField();
        txtSegundoAP = new javax.swing.JTextField();
        txtFechaNaci = new javax.swing.JFormattedTextField();
        txtTelefono = new javax.swing.JFormattedTextField();
        RBNombres = new javax.swing.JRadioButton();
        RBPrimerAP = new javax.swing.JRadioButton();
        RBSegundoAP = new javax.swing.JRadioButton();
        RBFechaNaci = new javax.swing.JRadioButton();
        RBTelefono = new javax.swing.JRadioButton();
        BBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        BActualizar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Editar persona");

        RBNombres.setText("Nombres");
        RBNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBNombresActionPerformed(evt);
            }
        });

        RBPrimerAP.setText("Primer apellido");
        RBPrimerAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBPrimerAPActionPerformed(evt);
            }
        });

        RBSegundoAP.setText("Segundo apellido");
        RBSegundoAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBSegundoAPActionPerformed(evt);
            }
        });

        RBFechaNaci.setText("Fecha de nacimiento");
        RBFechaNaci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBFechaNaciActionPerformed(evt);
            }
        });

        RBTelefono.setText("Telefono de contacto");
        RBTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTelefonoActionPerformed(evt);
            }
        });

        BBuscar.setText("Buscar");
        BBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBuscarActionPerformed(evt);
            }
        });

        jLabel4.setText("Primero has la busqueda");

        BActualizar.setText("Actualizar");
        BActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BActualizarActionPerformed(evt);
            }
        });

        jLabel5.setText("DNI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(BBuscar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RBPrimerAP)
                    .addComponent(RBSegundoAP)
                    .addComponent(RBFechaNaci)
                    .addComponent(RBTelefono)
                    .addComponent(RBNombres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombres)
                    .addComponent(txtPrimerAP)
                    .addComponent(txtSegundoAP)
                    .addComponent(txtTelefono)
                    .addComponent(txtFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BActualizar)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBNombres)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBPrimerAP)
                    .addComponent(txtPrimerAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBSegundoAP)
                    .addComponent(txtSegundoAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BActualizar))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBFechaNaci)
                    .addComponent(txtFechaNaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BBuscar))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(246, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BBuscarActionPerformed

    private void BActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BActualizarActionPerformed

    private void RBNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBNombresActionPerformed
        setEnabletextField(RBNombres);
    }//GEN-LAST:event_RBNombresActionPerformed

    private void RBPrimerAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBPrimerAPActionPerformed
        setEnabletextField(RBPrimerAP);
    }//GEN-LAST:event_RBPrimerAPActionPerformed

    private void RBSegundoAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBSegundoAPActionPerformed
        setEnabletextField(RBSegundoAP);
    }//GEN-LAST:event_RBSegundoAPActionPerformed

    private void RBFechaNaciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBFechaNaciActionPerformed
        setEnabletextField(RBFechaNaci);
    }//GEN-LAST:event_RBFechaNaciActionPerformed

    private void RBTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTelefonoActionPerformed
        setEnabletextField(RBTelefono);
    }//GEN-LAST:event_RBTelefonoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BActualizar;
    private javax.swing.JButton BBuscar;
    private javax.swing.JRadioButton RBFechaNaci;
    private javax.swing.JRadioButton RBNombres;
    private javax.swing.JRadioButton RBPrimerAP;
    private javax.swing.JRadioButton RBSegundoAP;
    private javax.swing.JRadioButton RBTelefono;
    private javax.swing.ButtonGroup groupBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JFormattedTextField txtFechaNaci;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtPrimerAP;
    private javax.swing.JTextField txtSegundoAP;
    private javax.swing.JFormattedTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
