/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.playwindow.proyecto_final_tallerbasesdatos.Vistas.PanelsPersona;

import com.playwindow.proyecto_final_tallerbasesdatos.Vistas.formatosTextArea;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JRadioButton;

/**
 *
 * @author daniel
 */
public class PersonaBaja extends javax.swing.JPanel {

    /**
     * Creates new form PersonaBaja
     */
    public PersonaBaja() {
        initComponents();
        grupoOpcion.add(RBDEpartamento);
        grupoOpcion.add(RBEspecialidad);
        grupoOpcion.add(RBRol);
        
        formatosTextArea.setSoloLetras(txtDepartamento, 70);
        formatosTextArea.setSoloLetras(txtEspecialidad, 45);
        formatosTextArea.setSoloNumeros(txtFieldID, 10);
        formatosTextArea.setSoloLetras(txtRol, 70);
        
        
    }
    
    public void setVaciarComponentes(){
        txtFieldID.setText("");
        txtDepartamento.setText("");
        txtEspecialidad.setText("");
        txtRol.setText("");
        grupoOpcion.clearSelection();
        
        setEnableRB(RBDEpartamento);
        setEnableRB(RBEspecialidad);
        setEnableRB(RBRol);
    }
    
        private void cleantxtdisable(){
        txtDepartamento.setEditable(false);
        txtEspecialidad.setEditable(false);
        txtRol.setEditable(false);
    }
    
    private void setEnableRB(JRadioButton select){
        boolean enabled = select.isSelected();
        if (select == (RBDEpartamento)){
            txtDepartamento.setEditable(enabled);
        }else if (select == (RBEspecialidad)){
            txtEspecialidad.setEditable(enabled);
        }else if (select == (RBRol)){
            txtRol.setEditable(enabled);
        }
    }
    
    public void setEnableRBFromGroup(ButtonGroup grupo) {                           // Metodo para abilitar/desbilitar campos de texto en base a RB dentro de un buttonGroup
    // 1. Obtener el ButtonModel seleccionado
    ButtonModel modeloSeleccionado = grupo.getSelection();

    if (modeloSeleccionado != null) {
        // 2. Iterar sobre los botones del grupo para encontrar el JRadioButton
        Enumeration<AbstractButton> botones = grupo.getElements();
        while (botones.hasMoreElements()) {
            AbstractButton boton = botones.nextElement();
            if (boton.getModel() == modeloSeleccionado) {
                // Se encontró el JRadioButton seleccionado
                if (boton instanceof JRadioButton) {
                    JRadioButton rbSeleccionado = (JRadioButton) boton;
                    
                    // Asegúrate de limpiar y deshabilitar los otros campos primero 
                    // para emular el comportamiento de un grupo de radio buttons
                    cleantxtdisable(); 
                    
                    // 3. Llamar a tu método existente
                    setEnableRB(rbSeleccionado);
                    
                    // Opcional: enfocar el campo de texto si está habilitado
                    // if (rbSeleccionado == RBNombres) txtNombres.requestFocusInWindow();
                    // ... y así sucesivamente para los demás RBs ...

                    break; // Salir del bucle una vez encontrado
                }
            }
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        grupoOpcion = new javax.swing.ButtonGroup();
        TittlePersonaBaja = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BDelete = new javax.swing.JButton();
        BBuscar = new javax.swing.JButton();
        txtFieldID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        RBRol = new javax.swing.JRadioButton();
        RBEspecialidad = new javax.swing.JRadioButton();
        RBDEpartamento = new javax.swing.JRadioButton();
        txtRol = new javax.swing.JTextField();
        txtEspecialidad = new javax.swing.JTextField();
        txtDepartamento = new javax.swing.JTextField();

        TittlePersonaBaja.setText("Elimiar persona");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BDelete.setText("Eliminar");
        BDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDeleteActionPerformed(evt);
            }
        });

        BBuscar.setText("Buscar");

        jLabel4.setText("ID");

        jLabel1.setText("Buscar personal por");

        RBRol.setText("Rol");
        RBRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBRolActionPerformed(evt);
            }
        });

        RBEspecialidad.setText("Especialidad");
        RBEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBEspecialidadActionPerformed(evt);
            }
        });

        RBDEpartamento.setText("Departamento");
        RBDEpartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBDEpartamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(TittlePersonaBaja))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RBEspecialidad)
                            .addComponent(RBRol)
                            .addComponent(RBDEpartamento))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRol)
                            .addComponent(txtEspecialidad)
                            .addComponent(txtDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addComponent(BBuscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BDelete)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(TittlePersonaBaja)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(BDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBRol)
                    .addComponent(txtRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBEspecialidad)
                    .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBDEpartamento)
                    .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BDeleteActionPerformed

    private void RBRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBRolActionPerformed
        setEnableRBFromGroup(grupoOpcion);
    }//GEN-LAST:event_RBRolActionPerformed

    private void RBEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBEspecialidadActionPerformed
        setEnableRBFromGroup(grupoOpcion);
    }//GEN-LAST:event_RBEspecialidadActionPerformed

    private void RBDEpartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBDEpartamentoActionPerformed
        setEnableRBFromGroup(grupoOpcion);
    }//GEN-LAST:event_RBDEpartamentoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBuscar;
    private javax.swing.JButton BDelete;
    private javax.swing.JRadioButton RBDEpartamento;
    private javax.swing.JRadioButton RBEspecialidad;
    private javax.swing.JRadioButton RBRol;
    private javax.swing.JLabel TittlePersonaBaja;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup grupoOpcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtFieldID;
    private javax.swing.JTextField txtRol;
    // End of variables declaration//GEN-END:variables
}
