/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.playwindow.proyecto_final_tallerbasesdatos.Vistas;

import com.playwindow.proyecto_final_tallerbasesdatos.Vistas.PanelsCitas.*;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author daniel
 */
public class CitEdit extends javax.swing.JInternalFrame {

    private String PanelAñadir = "CitaAñadir";
    private String PanelConsultar = "CitaConsultar";
    private String PanelModificar = "CitaModificar";
    private String PanelDeletCita = "CitaEliminar";
    private JPanel panelDeContenido;
    private CardLayout cardLayout;
    private CitaAñadir citAñadir = new CitaAñadir();
    private CitaModificar citModif = new CitaModificar();
    private CitaEliminar citDelet = new CitaEliminar();
    /**
     * Creates new form CitEdit
     */
    public CitEdit() {
        initComponents();
        iniciarCardLayaout();
        setWindowShow(1);
    }
    
    private void iniciarCardLayaout(){
        cardLayout = new CardLayout();
        panelDeContenido = new JPanel(cardLayout);
        
        panelDeContenido.add(citAñadir, PanelAñadir);
        panelDeContenido.add(citModif, PanelModificar);
        panelDeContenido.add(citDelet, PanelDeletCita );
        
        getContentPane().removeAll(); // quitamos el layout vacío generado por NetBeans
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(jToolBar1, BorderLayout.NORTH);
        getContentPane().add(panelDeContenido, BorderLayout.CENTER);
        
        revalidate();
        repaint();
    }
    
    private void showCardLayaout(String namePanel){
        cardLayout.show(panelDeContenido, namePanel);
        if(namePanel.equals(PanelAñadir)){
            citAñadir.setVaciarComponentes();
        }else if (namePanel.equals(PanelModificar)){
            citModif.setVaciarComponentes();
        }else if (namePanel.equals(PanelDeletCita)){
            citDelet.setVaciarcomponentes();
        }
    }
    
    public void setWindowShow(int numWindow){
        if (numWindow == 1){
            showCardLayaout(PanelAñadir);
            citAñadir.setVaciarComponentes();
        }else if (numWindow == 2){
            showCardLayaout(PanelModificar);
            citModif.setVaciarComponentes();
        }else if (numWindow == 3){
            showCardLayaout(PanelDeletCita);
            citDelet.setVaciarcomponentes();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        BNewCita = new javax.swing.JButton();
        BModifiCita = new javax.swing.JButton();
        BEliminiCita = new javax.swing.JButton();
        BModifiEstate = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        BNewCita.setText("Nueva");
        BNewCita.setFocusable(false);
        BNewCita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BNewCita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BNewCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNewCitaActionPerformed(evt);
            }
        });
        jToolBar1.add(BNewCita);

        BModifiCita.setText("Modificar");
        BModifiCita.setFocusable(false);
        BModifiCita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BModifiCita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BModifiCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModifiCitaActionPerformed(evt);
            }
        });
        jToolBar1.add(BModifiCita);

        BEliminiCita.setText("Eliminar");
        BEliminiCita.setFocusable(false);
        BEliminiCita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEliminiCita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BEliminiCita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEliminiCitaActionPerformed(evt);
            }
        });
        jToolBar1.add(BEliminiCita);

        BModifiEstate.setText("Consultar citas");
        BModifiEstate.setFocusable(false);
        BModifiEstate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BModifiEstate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BModifiEstate);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 451, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BNewCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNewCitaActionPerformed
        setWindowShow(1);
        citAñadir.setVaciarComponentes();
    }//GEN-LAST:event_BNewCitaActionPerformed

    private void BModifiCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModifiCitaActionPerformed
        setWindowShow(2);
        citModif.setVaciarComponentes();
    }//GEN-LAST:event_BModifiCitaActionPerformed

    private void BEliminiCitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEliminiCitaActionPerformed
        setWindowShow(3);
        citDelet.setVaciarcomponentes();
    }//GEN-LAST:event_BEliminiCitaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEliminiCita;
    private javax.swing.JButton BModifiCita;
    private javax.swing.JButton BModifiEstate;
    private javax.swing.JButton BNewCita;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
