/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.playwindow.proyecto_final_tallerbasesdatos.Vistas;

/**
 *
 * @author daniel
 */
public class CitEdit extends javax.swing.JInternalFrame {

    /**
     * Creates new form CitEdit
     */
    public CitEdit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        BNewCita = new javax.swing.JButton();
        BModifiCita = new javax.swing.JButton();
        BEliminiCita = new javax.swing.JButton();
        BModifiEstate = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        BNewCita.setText("Nueva");
        BNewCita.setFocusable(false);
        BNewCita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BNewCita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BNewCita);

        BModifiCita.setText("Modificar");
        BModifiCita.setFocusable(false);
        BModifiCita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BModifiCita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BModifiCita);

        BEliminiCita.setText("Eliminar");
        BEliminiCita.setFocusable(false);
        BEliminiCita.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BEliminiCita.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BEliminiCita);

        BModifiEstate.setText("Modificar estado");
        BModifiEstate.setFocusable(false);
        BModifiEstate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BModifiEstate.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(BModifiEstate);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 376, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BEliminiCita;
    private javax.swing.JButton BModifiCita;
    private javax.swing.JButton BModifiEstate;
    private javax.swing.JButton BNewCita;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
