/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.playwindow.proyecto_final_tallerbasesdatos.Vistas;

import com.playwindow.proyecto_final_tallerbasesdatos.Vistas.PanelsPaciente.*;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author daniel
 */
public class PacEdit extends javax.swing.JInternalFrame {
    private JPanel panelDeContenido;
    private CardLayout cardLayout;
    
    private final String panelAñadi = "PanelAñadirPaciente";
    private final String panelEdit = "PanelModificarPaciente";
    
    private PacienteAlta PacAlta = new PacienteAlta();
    private PacienteEdit pacModifi = new PacienteEdit();
    /**
     * Creates new form PacEdit
     */
    public PacEdit() {
        initComponents();
        
        this.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        iniciarCardLayaout();
    }

    private void iniciarCardLayaout(){
        cardLayout = new CardLayout();
        panelDeContenido = new JPanel(cardLayout);
        
        panelDeContenido.add(PacAlta, panelAñadi);
        panelDeContenido.add(pacModifi, panelEdit);
        
        getContentPane().removeAll(); // quitamos el layout vacío generado por NetBeans
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(jToolBar1, BorderLayout.NORTH);
        getContentPane().add(panelDeContenido, BorderLayout.CENTER);
        
        revalidate();
        repaint();
    }
    
    private void showCardLayaout(String namePanel){
        cardLayout.show(panelDeContenido, namePanel);
        if(namePanel.equals(panelAñadi)){
            PacAlta.setVaciarComponentes();
        }else if (namePanel.equals(panelEdit)){
            pacModifi.setVaciarComponentes();
        }
    }
    
    public void setWindowShow(int numWindow){
        if (numWindow == 1){
            showCardLayaout(panelAñadi);
            PacAlta.setVaciarComponentes();
        }else if (numWindow == 2){
            showCardLayaout(panelEdit);
            pacModifi.setVaciarComponentes();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        BAñadir = new javax.swing.JButton();
        BModifi = new javax.swing.JButton();

        setClosable(true);

        jToolBar1.setRollover(true);

        BAñadir.setText("Nuevo");
        BAñadir.setFocusable(false);
        BAñadir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BAñadir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAñadirActionPerformed(evt);
            }
        });
        jToolBar1.add(BAñadir);

        BModifi.setText("Modificar");
        BModifi.setFocusable(false);
        BModifi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        BModifi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        BModifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BModifiActionPerformed(evt);
            }
        });
        jToolBar1.add(BModifi);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAñadirActionPerformed
        showCardLayaout(panelAñadi);
    }//GEN-LAST:event_BAñadirActionPerformed

    private void BModifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BModifiActionPerformed
        showCardLayaout(panelEdit);
    }//GEN-LAST:event_BModifiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAñadir;
    private javax.swing.JButton BModifi;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
