/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.playwindow.proyecto_final_tallerbasesdatos.Vistas;

import com.playwindow.proyecto_final_tallerbasesdatos.Vistas.PanelsPersona.*;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.GroupLayout;
import javax.swing.JPanel;

/**
 *
 * @author daniel
 */
public class PersoEdit extends javax.swing.JInternalFrame {

    private JPanel panelDeContenido;
    private CardLayout cardLayout;
    
    public final String PanelAlta = "PanelAltaPersona";
    public final String PanelBaja = "PanelBajaPersona";
    public final String PanelEdit = "PanelEditPersona";
    public final String PanelConsult = "PanelConsultPersona";
    
    /**
     * Creates new form PersoEdit
     */
    public PersoEdit() {
        
        initComponents();
        iniciarCardLayout();
    }
    
    private void iniciarCardLayout() {
        cardLayout = new CardLayout();
        panelDeContenido = new JPanel(cardLayout);

        panelDeContenido.add(new PersonaAlta(), PanelAlta);
        panelDeContenido.add(new PersonaBaja(), PanelBaja);
        panelDeContenido.add (new PersonaEdit(), PanelEdit);

        getContentPane().removeAll(); // quitamos el layout vacío generado por NetBeans
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(panelDeContenido, BorderLayout.CENTER);
        
        cardLayout.show(panelDeContenido, PanelAlta);
        
        revalidate();
        repaint();
    }
    protected void setCardLayaout(String namePanel){
        cardLayout.show(panelDeContenido, namePanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("Añadir");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Eliminar");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Editar");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
