/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.playwindow.proyecto_final_tallerbasesdatos.Vistas;

/**
 *
 * @author daniel
 */
public class VentanaInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaInicio.class.getName());
    PersoEdit perEdit = new PersoEdit();
    

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        initComponents();
        perEdit.setVisible(true);
        destopPanel.add(perEdit);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        destopPanel = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuPersonal = new javax.swing.JMenu();
        PersonalAlta = new javax.swing.JMenuItem();
        PersonalBaja = new javax.swing.JMenuItem();
        PersonalConsulta = new javax.swing.JMenuItem();
        MenuCita = new javax.swing.JMenu();
        CitaAgendar = new javax.swing.JMenuItem();
        CitaConsulta = new javax.swing.JMenuItem();
        CitaEditar = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout destopPanelLayout = new javax.swing.GroupLayout(destopPanel);
        destopPanel.setLayout(destopPanelLayout);
        destopPanelLayout.setHorizontalGroup(
            destopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        destopPanelLayout.setVerticalGroup(
            destopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        MenuPersonal.setText("Personal");

        PersonalAlta.setText("Dar de alta");
        PersonalAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalAltaActionPerformed(evt);
            }
        });
        MenuPersonal.add(PersonalAlta);

        PersonalBaja.setText("Dar de baja");
        PersonalBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalBajaActionPerformed(evt);
            }
        });
        MenuPersonal.add(PersonalBaja);

        PersonalConsulta.setText("Consultar");
        MenuPersonal.add(PersonalConsulta);

        jMenuBar1.add(MenuPersonal);

        MenuCita.setText("Cita");

        CitaAgendar.setText("Egendar");
        CitaAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitaAgendarActionPerformed(evt);
            }
        });
        MenuCita.add(CitaAgendar);

        CitaConsulta.setText("Consultar");
        MenuCita.add(CitaConsulta);

        CitaEditar.setText("Editar");
        CitaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitaEditarActionPerformed(evt);
            }
        });
        MenuCita.add(CitaEditar);

        jMenuBar1.add(MenuCita);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(destopPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(destopPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PersonalAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalAltaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonalAltaActionPerformed

    private void PersonalBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalBajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonalBajaActionPerformed

    private void CitaAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitaAgendarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CitaAgendarActionPerformed

    private void CitaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitaEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CitaEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CitaAgendar;
    private javax.swing.JMenuItem CitaConsulta;
    private javax.swing.JMenuItem CitaEditar;
    private javax.swing.JMenu MenuCita;
    private javax.swing.JMenu MenuPersonal;
    private javax.swing.JMenuItem PersonalAlta;
    private javax.swing.JMenuItem PersonalBaja;
    private javax.swing.JMenuItem PersonalConsulta;
    private javax.swing.JDesktopPane destopPanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    // End of variables declaration//GEN-END:variables
}
