/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.playwindow.proyecto_final_tallerbasesdatos.Vistas.PanelsCitas;

/**
 *
 * @author daniel
 */
public class CitaConsultas extends javax.swing.JPanel {

    /**
     * Creates new form CitaConsultas
     */
    public CitaConsultas() {
        initComponents();
        
        BGBusquedaConsulta.add(RBBusquedaIDDoc);
        BGBusquedaConsulta.add(RBBusquedaIDPac);
        BGBusquedaConsulta.add(RBBusquedaNomDoc);
        BGBusquedaConsulta.add(RBBusquedaNomPac);
        BGBusquedaConsulta.add(RBBusquedaPAP);
        BGBusquedaConsulta.add(RBBusquedaPAPPac);
        BGBusquedaConsulta.add(RBBusquedaSAP);
        BGBusquedaConsulta.add(RBBusquedaSAP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGBusquedaConsulta = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        RBBusquedaIDDoc = new javax.swing.JRadioButton();
        RBBusquedaNomDoc = new javax.swing.JRadioButton();
        RBBusquedaPAP = new javax.swing.JRadioButton();
        RBBusquedaSAP = new javax.swing.JRadioButton();
        txtBusqIDDoc = new javax.swing.JTextField();
        txtBusqNomDoc = new javax.swing.JTextField();
        txtBusqPAP = new javax.swing.JTextField();
        txtBusqSAP = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        RBBusquedaIDPac = new javax.swing.JRadioButton();
        RBBusquedaNomPac = new javax.swing.JRadioButton();
        RBBusquedaPAPPac = new javax.swing.JRadioButton();
        RBBusqSAP = new javax.swing.JRadioButton();
        txtBusqIDPac = new javax.swing.JTextField();
        txtBusqNomPac = new javax.swing.JTextField();
        txtBusqPAPPac = new javax.swing.JTextField();
        txtBusqSAPPac = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("Buscar citas");

        jLabel2.setText("Selecciona el criterio de busqueda");

        jLabel3.setText("Doctor");

        RBBusquedaIDDoc.setText("ID doctor");
        RBBusquedaIDDoc.setToolTipText("");
        RBBusquedaIDDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBBusquedaIDDocActionPerformed(evt);
            }
        });

        RBBusquedaNomDoc.setText("Nombre");

        RBBusquedaPAP.setText("Primer apellido");

        RBBusquedaSAP.setText("Segundo apellido");

        jLabel4.setText("Paciente");

        RBBusquedaIDPac.setText("ID paciente");
        RBBusquedaIDPac.setToolTipText("");

        RBBusquedaNomPac.setText("Nombre");

        RBBusquedaPAPPac.setText("primer apellido");

        RBBusqSAP.setText("Segundo apellido");
        RBBusqSAP.setToolTipText("");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Resultados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(196, 196, 196))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RBBusquedaPAP)
                            .addComponent(RBBusquedaNomDoc)
                            .addComponent(RBBusquedaIDDoc)
                            .addComponent(RBBusquedaSAP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBusqIDDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(txtBusqNomDoc)
                            .addComponent(txtBusqPAP)
                            .addComponent(txtBusqSAP))
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RBBusquedaIDPac)
                            .addComponent(RBBusquedaNomPac)
                            .addComponent(RBBusquedaPAPPac)
                            .addComponent(RBBusqSAP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBusqSAPPac, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(txtBusqPAPPac)
                            .addComponent(txtBusqNomPac)
                            .addComponent(txtBusqIDPac)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jLabel5)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBBusquedaIDDoc)
                    .addComponent(txtBusqIDDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBBusquedaIDPac)
                    .addComponent(txtBusqIDPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBBusquedaNomDoc)
                    .addComponent(txtBusqNomDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBBusquedaNomPac)
                    .addComponent(txtBusqNomPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBBusquedaPAP)
                    .addComponent(txtBusqPAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBBusquedaPAPPac)
                    .addComponent(txtBusqPAPPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RBBusquedaSAP)
                    .addComponent(txtBusqSAP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RBBusqSAP)
                    .addComponent(txtBusqSAPPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RBBusquedaIDDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBBusquedaIDDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RBBusquedaIDDocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGBusquedaConsulta;
    private javax.swing.JRadioButton RBBusqSAP;
    private javax.swing.JRadioButton RBBusquedaIDDoc;
    private javax.swing.JRadioButton RBBusquedaIDPac;
    private javax.swing.JRadioButton RBBusquedaNomDoc;
    private javax.swing.JRadioButton RBBusquedaNomPac;
    private javax.swing.JRadioButton RBBusquedaPAP;
    private javax.swing.JRadioButton RBBusquedaPAPPac;
    private javax.swing.JRadioButton RBBusquedaSAP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBusqIDDoc;
    private javax.swing.JTextField txtBusqIDPac;
    private javax.swing.JTextField txtBusqNomDoc;
    private javax.swing.JTextField txtBusqNomPac;
    private javax.swing.JTextField txtBusqPAP;
    private javax.swing.JTextField txtBusqPAPPac;
    private javax.swing.JTextField txtBusqSAP;
    private javax.swing.JTextField txtBusqSAPPac;
    // End of variables declaration//GEN-END:variables
}
