/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.playwindow.proyecto_final_tallerbasesdatos.Vistas.PanelsCitas;

import com.playwindow.proyecto_final_tallerbasesdatos.Vistas.*;

import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JRadioButton;

/**
 *
 * @author daniel
 */
public class CitaModificar extends javax.swing.JPanel {

    /**
     * Creates new form CitaModificar
     */
    public CitaModificar() {
        initComponents();
        BGBuscar.add(RBIDPaciente);
        BGBuscar.add(RBIDdoctor);
        formatosTextArea.FormatoFecha(txtFecha);
        formatosTextArea.FormatoHora(txtHora);
        formatosTextArea.setSoloAlfanumericos(txtNumSeguro, 10);
        formatosTextArea.setSoloNumeros(txtIDCita, 10);
        formatosTextArea.setSoloNumeros(txtIDDoc, 10);
        formatosTextArea.setSoloNumeros(txtIDPac, 10);
        formatosTextArea.setSoloLetras(txtEstado, 40);
    }
    
    public void setVaciarComponentes(){
        txtFecha.setText("");
        txtHora.setText("");
        txtIDCita.setText("");
        txtIDDoc.setText("");
        txtIDPac.setText("");
        txtNumSeguro.setText("");
        txtEstado.setText("");
        CBDoctor.setSelectedIndex(0);
        setEnableRBFromGroup(BGBuscar);
    }
    private void setEnableRB(JRadioButton RBSelect){
        boolean enable = RBSelect.isSelected();
        if (RBSelect == RBIDPaciente){
            txtIDPac.setEditable(enable);
        }else if (RBSelect == RBIDdoctor){
            txtIDDoc.setEditable(enable);
        }
    }
    
    private void cleantxtdisable(){
        RBIDPaciente.setSelected(false);
        RBIDdoctor.setSelected(false);
    }
    
    public void setEnableRBFromGroup(ButtonGroup grupo) {                           // Metodo para abilitar/desbilitar campos de texto en base a RB dentro de un buttonGroup
    // 1. Obtener el ButtonModel seleccionado
    ButtonModel modeloSeleccionado = grupo.getSelection();

    if (modeloSeleccionado != null) {
        // 2. Iterar sobre los botones del grupo para encontrar el JRadioButton
        Enumeration<AbstractButton> botones = grupo.getElements();
        while (botones.hasMoreElements()) {
            AbstractButton boton = botones.nextElement();
            if (boton.getModel() == modeloSeleccionado) {
                // Se encontró el JRadioButton seleccionado
                if (boton instanceof JRadioButton) {
                    JRadioButton rbSeleccionado = (JRadioButton) boton;
                    
                    // Asegúrate de limpiar y deshabilitar los otros campos primero 
                    // para emular el comportamiento de un grupo de radio buttons
                    cleantxtdisable(); 
                    
                    // 3. Llamar a tu método existente
                    setEnableRB(rbSeleccionado);
                    
                    // Opcional: enfocar el campo de texto si está habilitado
                    // if (rbSeleccionado == RBNombres) txtNombres.requestFocusInWindow();
                    // ... y así sucesivamente para los demás RBs ...

                    break; // Salir del bucle una vez encontrado
                }
            }
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGBuscar = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDPac = new javax.swing.JTextField();
        RBIDPaciente = new javax.swing.JRadioButton();
        RBIDdoctor = new javax.swing.JRadioButton();
        txtIDDoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIDCita = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CBDoctor = new javax.swing.JComboBox<>();
        txtFecha = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtHora = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtNumSeguro = new javax.swing.JTextField();
        BCargar = new javax.swing.JButton();
        BBuscar = new javax.swing.JButton();
        BGuardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();

        jLabel1.setText("Modificar cita");

        jLabel2.setText("Buscar");

        RBIDPaciente.setText("ID paciente");
        RBIDPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBIDPacienteActionPerformed(evt);
            }
        });

        RBIDdoctor.setText("ID doctor");
        RBIDdoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBIDdoctorActionPerformed(evt);
            }
        });

        jLabel3.setText("Cargar");

        jLabel4.setText("ID cita");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Doctor");

        jLabel6.setText("Fecha");

        CBDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Hora");

        jLabel8.setText("Numero de seguro");

        BCargar.setText("Cargar");

        BBuscar.setText("Buscar");

        BGuardar.setText("Guardar");

        jLabel9.setText("Estado");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(RBIDdoctor)
                                            .addComponent(RBIDPaciente))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtIDDoc, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                            .addComponent(txtIDPac)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtIDCita, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jLabel3))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(BCargar)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(BBuscar)
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFecha)
                            .addComponent(CBDoctor, 0, 90, Short.MAX_VALUE)
                            .addComponent(txtHora)
                            .addComponent(txtNumSeguro)
                            .addComponent(txtEstado))
                        .addGap(39, 39, 39)
                        .addComponent(BGuardar)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtIDCita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BCargar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtIDPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(RBIDPaciente)
                                            .addComponent(jLabel5)
                                            .addComponent(CBDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(RBIDdoctor)
                                            .addComponent(txtIDDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)
                                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(BBuscar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BGuardar)
                                .addGap(22, 22, 22)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNumSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RBIDPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBIDPacienteActionPerformed
        setEnableRBFromGroup(BGBuscar);
    }//GEN-LAST:event_RBIDPacienteActionPerformed

    private void RBIDdoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBIDdoctorActionPerformed
        setEnableRBFromGroup(BGBuscar);
    }//GEN-LAST:event_RBIDdoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BBuscar;
    private javax.swing.JButton BCargar;
    private javax.swing.ButtonGroup BGBuscar;
    private javax.swing.JButton BGuardar;
    private javax.swing.JComboBox<String> CBDoctor;
    private javax.swing.JRadioButton RBIDPaciente;
    private javax.swing.JRadioButton RBIDdoctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JFormattedTextField txtHora;
    private javax.swing.JTextField txtIDCita;
    private javax.swing.JTextField txtIDDoc;
    private javax.swing.JTextField txtIDPac;
    private javax.swing.JTextField txtNumSeguro;
    // End of variables declaration//GEN-END:variables
}
